//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastsport.vn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fastsport_dbEntities : DbContext
    {
        public fastsport_dbEntities()
            : base("name=fastsport_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<about> abouts { get; set; }
        public virtual DbSet<account_admin> account_admin { get; set; }
        public virtual DbSet<account_customer> account_customer { get; set; }
        public virtual DbSet<chi_tiet_hoa_don> chi_tiet_hoa_don { get; set; }
        public virtual DbSet<color> colors { get; set; }
        public virtual DbSet<don_dat_hang> don_dat_hang { get; set; }
        public virtual DbSet<hoa_don> hoa_don { get; set; }
        public virtual DbSet<khach_hang> khach_hang { get; set; }
        public virtual DbSet<loai_san_pham> loai_san_pham { get; set; }
        public virtual DbSet<nhom_sp> nhom_sp { get; set; }
        public virtual DbSet<san_pham> san_pham { get; set; }
        public virtual DbSet<size> sizes { get; set; }
        public virtual DbSet<trang_thai_ddh> trang_thai_ddh { get; set; }
        public virtual DbSet<trang_thai_sp> trang_thai_sp { get; set; }
        public virtual DbSet<chi_tiet_don_dat_hang> chi_tiet_don_dat_hang { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
